### PR TITLE
latest calendar.civix.php

### PR DESCRIPTION
**Pull request by jmcclelland**
This update fixes php 7.4 deprecation warnings.

### CODE REVIEW

**Comment by mlutfy** [comment]
hi @AWG-Bohdan, would it be possible to merge this PR, and tag a new release? It is important for PHP 8.

More context: https://civicrm.org/blog/bgm/php-8-support-civicrm-extensions

If you do not have time, I can help move the extension to Gitlab, so that we can do minor maintenance fixes. Otherwise, we will have to remove the "reviewed" flag from the CiviCRM extension directory,

**Comment by mlutfy** [comment]
Hi @AWG-Bohdan , could you merge this PR and tag a new release? It's important for PHP 8 compatibility. 

If you are busy, I would be happy to help maintain this extension, to fix small issues like this (and #28 ). I would move the extension to lab.civicrm.org (if you add me as an owner on this project so that I can import the full history).

For more information:  
https://civicrm.org/blog/bgm/php-8-support-civicrm-extensions

Thanks!

**Comment by mlutfy** [comment]
I removed the "reviewed" status from the extension until a new version is realeased (https://civicrm.org/extensions/civicalendar) - otherwise it might crash an installation. Ping me when it's fixed, and I'll add the status back.

**Comment by AWG-Bohdan** [comment]
We moved the project to CiviCRM's Gitlab.

**Pull request closed without merging**
